name: revo
description: "An android dialer application made with Flutter following MDY MD3 guidelines."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: ^1.8.1
  google_fonts: ^6.3.3
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  flutter_riverpod: ^3.1.0
  riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.1.0
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  simple_barcode_scanner: ^0.4.0
  qr_flutter: ^4.1.0
  flutter_contacts: ^1.1.9+2
  flutter_sim_data: ^1.0.5
  call_log : ^6.0.1
  share_plus: ^12.0.1
  android_intent_plus: ^6.0.0

  # Replace these with better packages
  fluentui_system_icons: ^1.1.273
  font_awesome_flutter: ^10.12.0
  sticky_az_list:
    git:
      url: https://github.com/user-grinch/sticky_az_list_plus
      ref: '241d5c9'

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21 

flutter_native_splash:
  image: 'assets/splash.png'
  color: "#FFFFFF"  
  image_dark: 'assets/splash.png'
  color_dark: "#000000"  
  # branding: 'assets/branding.png'

  android_12:
    image: 'assets/splash.png'
    color: "#FFFFFF"  
    image_dark: 'assets/splash.png'
    color_dark: "#000000" 
    # branding: 'assets/branding.png'

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  riverpod_generator: ^4.0.0+1
  flutter_launcher_icons: ^0.14.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
